@startuml Version 0.1.0

class Player extends Phaser.Physics.Arcade.Sprite {
    # initMovement(): void
    + Player()
}

note left of Player::Player
    Calls initMovement
end note

class Phaser.GameObjects.Image <<terrain image>>
class Phaser.Cameras.Scene2D.Camera

Phaser.Cameras.Scene2D.Camera ..> Player: startFollow()

@enduml